import type { FundRow, ProposalRow } from "./types";

export const SEED_FUNDS: FundRow[] = [
  {
    id: "fund-demo-1",
    manager: "Manager::alpha",
    totalCapital: 1_250_000,
    investors: ["Investor::a", "Investor::b", "Investor::c", "Investor::f", "Investor::g"],
    investorsCount: 5,
    treasuryBalance: 945_000,
  },
  {
    id: "fund-demo-2",
    manager: "Manager::beta",
    totalCapital: 640_000,
    investors: ["Investor::d", "Investor::e", "Investor::h"],
    investorsCount: 3,
    treasuryBalance: 595_000,
  },
  {
    id: "fund-demo-3",
    manager: "Manager::gamma",
    totalCapital: 2_100_000,
    investors: [
      "Investor::i",
      "Investor::j",
      "Investor::k",
      "Investor::l",
      "Investor::m",
      "Investor::n",
      "Investor::o",
    ],
    investorsCount: 7,
    treasuryBalance: 1_780_000,
  },
];

export const SEED_PROPOSALS: ProposalRow[] = [
  {
    id: "prop-demo-1",
    fundId: "fund-demo-1",
    description: "Allocate 120k to structured notes sleeve",
    amount: 120_000,
    yesVotes: 14,
    noVotes: 3,
    executed: false,
    proposer: "Allocator::p1",
  },
  {
    id: "prop-demo-2",
    fundId: "fund-demo-1",
    description: "Rebalance public equities band ±4%",
    amount: 45_000,
    yesVotes: 22,
    noVotes: 1,
    executed: true,
    proposer: "Allocator::p2",
  },
  {
    id: "prop-demo-3",
    fundId: "fund-demo-2",
    description: "Treasury buffer top-up",
    amount: 25_000,
    yesVotes: 5,
    noVotes: 7,
    executed: false,
    proposer: "Allocator::p3",
  },
  {
    id: "prop-demo-4",
    fundId: "fund-demo-1",
    description: "Increase private credit allocation by 8%",
    amount: 180_000,
    yesVotes: 19,
    noVotes: 4,
    executed: true,
    proposer: "Allocator::p1",
  },
  {
    id: "prop-demo-5",
    fundId: "fund-demo-2",
    description: "Add tokenized treasuries sleeve (90-day)",
    amount: 60_000,
    yesVotes: 11,
    noVotes: 2,
    executed: true,
    proposer: "Allocator::p4",
  },
  {
    id: "prop-demo-6",
    fundId: "fund-demo-3",
    description: "Seed real-estate co-investment vehicle",
    amount: 320_000,
    yesVotes: 17,
    noVotes: 6,
    executed: true,
    proposer: "Allocator::p5",
  },
  {
    id: "prop-demo-7",
    fundId: "fund-demo-3",
    description: "Open 250k venture sleeve — AI infra",
    amount: 250_000,
    yesVotes: 21,
    noVotes: 3,
    executed: false,
    proposer: "Allocator::p2",
  },
  {
    id: "prop-demo-8",
    fundId: "fund-demo-3",
    description: "Hedge USD exposure with FX forwards",
    amount: 75_000,
    yesVotes: 9,
    noVotes: 12,
    executed: false,
    proposer: "Allocator::p6",
  },
  {
    id: "prop-demo-9",
    fundId: "fund-demo-1",
    description: "Quarterly distribution to LPs",
    amount: 90_000,
    yesVotes: 16,
    noVotes: 2,
    executed: false,
    proposer: "Allocator::p2",
  },
  {
    id: "prop-demo-10",
    fundId: "fund-demo-2",
    description: "Sunset legacy bond ladder by Q3",
    amount: 40_000,
    yesVotes: 8,
    noVotes: 8,
    executed: false,
    proposer: "Allocator::p3",
  },
];
